# Generated by Django 5.0 on 2023-12-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_usuarios_is_admin_usuarios_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='activo_con_email_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(blank=True, null=True),
        ),
    ]
