# Generated by Django 5.0 on 2023-12-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usuarios_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='cargo',
            field=models.CharField(default='Empleado', max_length=50),
        ),
    ]
