# Generated by Django 5.0 on 2023-12-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_usuarios_is_admin_usuarios_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
