# Generated by Django 5.0 on 2024-01-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usuarios_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='codigo_activar_cuenta',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='codigo_recuperar_cuenta',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
