# Generated by Django 5.0 on 2023-12-18 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info_ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos', models.JSONField()),
                ('ganancia_total', models.DecimalField(decimal_places=2, max_digits=500)),
                ('venta_finalizada', models.BooleanField(default=False)),
                ('info_ventas', models.ManyToManyField(null=True, to='ventas.info_ventas')),
                ('mesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.mesas')),
            ],
        ),
    ]
