# Generated by Django 5.0 on 2023-12-19 23:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ventas',
            name='info_ventas',
            field=models.ManyToManyField(to='ventas.info_ventas'),
        ),
    ]
