# Generated by Django 5.0 on 2023-12-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_ventas_fecha_creacion_alter_ventas_info_ventas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='info_ventas',
            field=models.ManyToManyField(null=True, to='ventas.info_ventas'),
        ),
    ]
