# Generated by Django 5.0 on 2023-12-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_ventas_info_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
