# Generated by Django 5.0 on 2023-12-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_ventas_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
