# Generated by Django 5.0 on 2023-12-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=250, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=500)),
                ('cantidad_disponible', models.PositiveBigIntegerField()),
                ('creador', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
        ),
    ]
